### ISSUE TITLE
be able to share a single event

### ISSUE THREAD

**Issue by Gunstick** [Kaweechelchen/Level2.lu#22]
Share a single event either by the classic twitter, facebook etc buttons or by being able to get an URL for the single event.
The single event page could be something reachable through "details" link which shows the same description and stuff, plus a short info about level2 location, map, directions and other merchandizing seen on the main level2.lu page.

**Comment by Kaweechelchen** [comment]
Already done in https://github.com/syn2cat/Level2.lu/commit/46355ae9799e5a22efecaa66eede3059c60f941d

![screen shot 2015-07-07 at 8 45 07 am](https://cloud.githubusercontent.com/assets/781648/8540309/b978005c-2484-11e5-8050-3210c1c8877f.png)
